
- name: Create mongodb repofile
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/
    mode: '0755'

- name: install mongoshell package 
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: latest
  
- name: Create catalogue database
  ansible.builtin.shell: mongo --host {{ lookup('amazon.aws.aws_ssm', 'mongoip', region='us-east-1')  }}:27017 --username Harsha --password {{ lookup('amazon.aws.aws_ssm', 'docdbpass', region='us-east-1')  }} </app/schema/{{component}}.js
