- name: Run Nodejs shell script
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodejs package 
  ansible.builtin.yum:
    name: nodejs
    state: latest
