- name: Install golang
  ansible.builtin.dnf:
    name: golang
    state: present

- name: Create user and download application code
  ansible.builtin.import_role:
    name: common
    tasks_from: user

- name: Install dependencies
  ansible.builtin.shell: |
    go mod init dispatch
    go get 
    go build
  args:
    chdir: /app

- name: Configure and start dispatch service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

